/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tds_hom_switchable_Switchable */

#ifndef _Included_tds_hom_switchable_Switchable
#define _Included_tds_hom_switchable_Switchable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tds_hom_switchable_Switchable_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_tds_hom_switchable_Switchable_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    addToMulNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_switchable_Switchable_addToMulNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    addToOpeNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_switchable_Switchable_addToOpeNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    mulToAddNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_switchable_Switchable_mulToAddNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    mulToOpeNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_switchable_Switchable_mulToOpeNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    opeToAddNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_switchable_Switchable_opeToAddNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    opeToMulNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_switchable_Switchable_opeToMulNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_switchable_Switchable
 * Method:    bytesToZZString
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tds_hom_switchable_Switchable_bytesToZZString
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
