/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tds_hom_Paillier */

#ifndef _Included_tds_hom_Paillier
#define _Included_tds_hom_Paillier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tds_hom_Paillier
 * Method:    keygen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tds_hom_Paillier_keygen
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     tds_hom_Paillier
 * Method:    init_public_key
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tds_hom_Paillier_init_1public_1key
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tds_hom_Paillier
 * Method:    init_private_key
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tds_hom_Paillier_init_1private_1key
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tds_hom_Paillier
 * Method:    encrypt
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_Paillier_encrypt
  (JNIEnv *, jobject, jint);

/*
 * Class:     tds_hom_Paillier
 * Method:    add
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_Paillier_add
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tds_hom_Paillier
 * Method:    subtract
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_Paillier_subtract
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tds_hom_Paillier
 * Method:    decryptToString
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tds_hom_Paillier_decryptToString
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
