/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tds_hom_Ope */

#ifndef _Included_tds_hom_Ope
#define _Included_tds_hom_Ope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tds_hom_Ope
 * Method:    init
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_tds_hom_Ope_init
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     tds_hom_Ope
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_Ope_encrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_Ope
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_Ope_decrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
