/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tds_hom_Elgamal */

#ifndef _Included_tds_hom_Elgamal
#define _Included_tds_hom_Elgamal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tds_hom_Elgamal
 * Method:    keygen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tds_hom_Elgamal_keygen
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     tds_hom_Elgamal
 * Method:    init_public_key
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tds_hom_Elgamal_init_1public_1key
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tds_hom_Elgamal
 * Method:    init_private_key
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tds_hom_Elgamal_init_1private_1key
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tds_hom_Elgamal
 * Method:    encrypt
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_Elgamal_encrypt
  (JNIEnv *, jobject, jint);

/*
 * Class:     tds_hom_Elgamal
 * Method:    multiply
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tds_hom_Elgamal_multiply
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tds_hom_Elgamal
 * Method:    decrypt
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_tds_hom_Elgamal_decrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tds_hom_Elgamal
 * Method:    decryptToString
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tds_hom_Elgamal_decryptToString
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
